### ISSUE TITLE
Static resource handling

### ISSUE THREAD

**Issue by it-xtech-dev** [aspnet/AspNetCore.Docs.pl-pl#19]
For core 3.0 there are some mentions about serving static assets - here i cannot find any. Can you provide some examples how to solve this issue?

I have used this approach: https://stackoverflow.com/questions/51610513/can-razor-class-library-pack-static-files-js-css-etc-too

This works fine when RCL is referenced as project but fails for nuget packaged library (resources not found except those provided by host app).

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Interfejs użytkownika Razor wielokrotnego użytku w bibliotekach klas z ASP.NET Core](https://docs.microsoft.com/pl-pl/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @it-xtech-dev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @it-xtech-dev

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/15877

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by it-xtech-dev** [comment]
Thanks for moving this issue to right thread.
